[package]
name = "neural_analytics_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
neural_analytics_model = { path = "../neural_analytics_model" }

tapo = "0.8.0"
chrono = "0.4.38"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "signal",
] }

presage = "0.3.0"
async-trait = "0.1.88"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
statig = { version = "0.3.0", features = ["serde", "std", "async"] }
brainflow = { git = "https://github.com/brainflow-dev/brainflow", package = "brainflow" }
log = "0.4.17"
rand = "0.8"
once_cell = "1.18.0"
tract-onnx = "0.21.1"
ndarray = "0.15.6"
anyhow = "1.0.75"
