[package]
name = "neural_analytics_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
neural_analytics_model = { path = "../neural_analytics_model" }

tapo = "0.8.0"
chrono = "0.4.38"
blackbox_di = "0.1.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "signal"] }

presage = "0.3.0"
async-trait = "0.1.88"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
statig = { version = "0.3.0", features = ["serde", "std", "async"] }
brainflow = { path = "/Users/neirth/Vendors/brainflow/rust_package/brainflow" }
tract = "0.21.9"
log = "0.4.17"
