[package]
name = "neural_analytics_gui"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Martinez <7413024+Neirth@users.noreply.github.com>"]
description = "GUI interface for Neural Analytics project"

[dependencies]
# GUI dependencies
slint = { version = "1.10.0", default-features = true, features = ["renderer-skia"] }
presage = "0.3.0"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "signal"] }
plotters = "0.3.7"

# Workspace dependencies
neural_analytics_core = { path = "../neural_analytics_core" }

[build-dependencies]
slint-build = "1.10.0"

[[bin]]
name = "neural_analytics_gui"
path = "src/main.rs"